"""Remove passwords

Revision ID: 2d5fd3e4cac8
Revises: 44a70fa979b
Create Date: 2012-09-20 12:03:33.030164

"""

# revision identifiers, used by Alembic.
revision = '2d5fd3e4cac8'
down_revision = '44a70fa979b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', u'password')
    op.drop_column('users', u'key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'key', sa.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column(u'password', sa.VARCHAR(length=80), nullable=True))
    ### end Alembic commands ###
