"""empty message

Revision ID: 30acbd4e5b0f
Revises: 44a70fa979b
Create Date: 2012-09-19 20:27:57.004004

"""

# revision identifiers, used by Alembic.
revision = '30acbd4e5b0f'
down_revision = '44a70fa979b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'contact_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    ### end Alembic commands ###
