"""more cascade deletes

Revision ID: 341de5dd1b60
Revises: 39440ceaa03c
Create Date: 2012-09-12 01:17:38.215326

"""

# revision identifiers, used by Alembic.
revision = '341de5dd1b60'
down_revision = '39440ceaa03c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE photos_tags
        DROP CONSTRAINT photos_tags_photo_id_fkey,
        ADD CONSTRAINT photos_tags_photo_id_fkey
            FOREIGN KEY (photo_id)
            REFERENCES photos (id)
                ON UPDATE NO ACTION
                ON DELETE CASCADE;

    ALTER TABLE photos_tags
        DROP CONSTRAINT photos_tags_tag_id_fkey,
        ADD CONSTRAINT photos_tags_tag_id_fkey
            FOREIGN KEY (tag_id)
            REFERENCES tags (id)
                ON UPDATE NO ACTION
                ON DELETE CASCADE;


    ALTER TABLE photos_users
        DROP CONSTRAINT photos_users_photo_id_fkey,
        ADD CONSTRAINT photos_users_photo_id_fkey
            FOREIGN KEY (photo_id)
            REFERENCES photos (id)
                ON UPDATE NO ACTION
                ON DELETE CASCADE;

    ALTER TABLE photos_users
        DROP CONSTRAINT photos_users_user_id_fkey,
        ADD CONSTRAINT photos_users_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES users (id)
                ON UPDATE NO ACTION
                ON DELETE CASCADE;
     """)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE photos_tags
        DROP CONSTRAINT photos_tags_photo_id_fkey,
        ADD CONSTRAINT photos_tags_photo_id_fkey
            FOREIGN KEY (photo_id)
            REFERENCES photos (id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;

    ALTER TABLE photos_tags
        DROP CONSTRAINT photos_tags_tag_id_fkey,
        ADD CONSTRAINT photos_tags_tag_id_fkey
            FOREIGN KEY (tag_id)
            REFERENCES tags (id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;


    ALTER TABLE photos_users
        DROP CONSTRAINT photos_users_photo_id_fkey,
        ADD CONSTRAINT photos_users_photo_id_fkey
            FOREIGN KEY (photo_id)
            REFERENCES photos (id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;

    ALTER TABLE photos_users
        DROP CONSTRAINT photos_users_user_id_fkey,
        ADD CONSTRAINT photos_users_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES users (id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION;
    """)

    ### end Alembic commands ###
