"""empty message

Revision ID: 44a70fa979b
Revises: 341de5dd1b60
Create Date: 2012-09-12 07:48:33.071284

"""

# revision identifiers, used by Alembic.
revision = '44a70fa979b'
down_revision = '341de5dd1b60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('is_public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'is_public')
    ### end Alembic commands ###
